export const VELOCITY_DIFF: number = 3
export const AIR_RESISTANCE_FACTOR: number = 0.9999
export const PROJECTILES_COLLISION_GROUP_NAME = "Projectiles"
export const PLAYERS_COLLISION_GROUP_NAME = "Players"

export const PLAYER_THROW_BALL_VELOCITY_FACTOR = 1.5
export const PLAYER_MAX_POWER_LEVEL = 10
export const PLAYER_MIN_POWER_LEVEL = 0
export const PLAYER_MAX_POWER_NUM_MILLISECONDS = 2000
export const PLAYER_MIN_POWER_NUM_MILLISECONDS = 500

export const PROJECTILE_IDLE_VELOCITY = 1
export const PROJECTILE_MAX_SPEED = 700
export const PROJECTILE_MIN_SPEED = 100

export const LAUNCHER_VELOCTY = 200